# Generated by Django 6.0.1 on 2026-01-09 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, help_text='e.g., Peanuts, Dairy, Shellfish')),
                ('restrictions', models.TextField(blank=True, help_text='e.g., Gluten-Free, Vegan, Low-FODMAP')),
                ('health_goals', models.TextField(blank=True, help_text='e.g., Weight loss, Muscle gain')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
