# Generated by Django 6.0.1 on 2026-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0004_userprofile_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_scan_date',
            field=models.DateField(auto_now=True),
        ),
    ]
