# Generated by Django 6.0.1 on 2026-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0005_userprofile_daily_scan_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='e.g., Peanuts, Dairy'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_goals',
            field=models.TextField(blank=True, help_text='e.g., Weight loss'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='restrictions',
            field=models.TextField(blank=True, help_text='e.g., Gluten-Free, Vegan'),
        ),
    ]
